baseurl:
title: YKode
subtitle: Healthy Dose of Programming Related Stuffs
author: Didiet Noor
simple_search: http://google.com/search
description: Healthy Dose of Programming Related Stuff 
name: Ykode
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /:year/:month/:day/:title.html 
timezone: Asia/Jakarta
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: mvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/

disqus: ykode

google: 
  site_verification: GJKUuI9BF9gJkW8MXtIjmey5capg1KjtaKjhb7kBcqU
  analytics: UA-21914048-1

twitter:
  site: ykode
  author: lynxluna
